// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8cXG9ccQyn-8eG9UvjdSdTQ_hUg0ESxs',
    appId: '1:760351838906:web:4a64d128a3ede2707b6883',
    messagingSenderId: '760351838906',
    projectId: 'appfire-c1ecf',
    authDomain: 'appfire-c1ecf.firebaseapp.com',
    storageBucket: 'appfire-c1ecf.firebasestorage.app',
    measurementId: 'G-QFRCSTD9QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXApkGS8c1r7b_F-uj4XlFN6eU2psxqc',
    appId: '1:760351838906:android:61662f294711cf467b6883',
    messagingSenderId: '760351838906',
    projectId: 'appfire-c1ecf',
    storageBucket: 'appfire-c1ecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3tn99FgOFRmP06oXdSdKhnSKI_alts_Y',
    appId: '1:760351838906:ios:e8e9f7abc41b064a7b6883',
    messagingSenderId: '760351838906',
    projectId: 'appfire-c1ecf',
    storageBucket: 'appfire-c1ecf.firebasestorage.app',
    iosBundleId: 'com.example.appBdFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3tn99FgOFRmP06oXdSdKhnSKI_alts_Y',
    appId: '1:760351838906:ios:e8e9f7abc41b064a7b6883',
    messagingSenderId: '760351838906',
    projectId: 'appfire-c1ecf',
    storageBucket: 'appfire-c1ecf.firebasestorage.app',
    iosBundleId: 'com.example.appBdFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8cXG9ccQyn-8eG9UvjdSdTQ_hUg0ESxs',
    appId: '1:760351838906:web:179c881088df07f27b6883',
    messagingSenderId: '760351838906',
    projectId: 'appfire-c1ecf',
    authDomain: 'appfire-c1ecf.firebaseapp.com',
    storageBucket: 'appfire-c1ecf.firebasestorage.app',
    measurementId: 'G-1D83NCFS5T',
  );

}